### ISSUE TITLE
Create readme for project

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/ListOfGoods#1]
I'm as a developer and a good guy wanna to have README file about my project.
I should contains:
1. Main topic of the project
2. Technology stack
3. How to build
4. How to execute.

Estimation time for issue: 2 hours.

**Comment by aleksieiev** [comment]
Ready for PR review: https://github.com/java-fat-unicorn-team/ListOfGoods/pull/2

**Comment by maksimk99** [comment]
I finally read about GIT and deleted all files from master branch.
I replaced my first commit with new which contains only README.md and .gitignore
