### ISSUE TITLE
Add build at TravicCI

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/ListOfGoods#11]
As a product owner I want to see current build status of my project. I choose TravisCI as a free software for it.
Task: integration with TravisCI. Each commit at least in master should execute TravisCI task and README file should contains label from TravisCI about latest build status

Please, comment estimation for this task. Keep in mind that you need to learn what is CI in general and fully configure Travis according your needs. It's important to understand CI process

**Comment by maksimk99** [comment]
estimation time: 8 hours

**Comment by aleksieiev** [comment]
@maksimk99 
1. According to build report ( https://travis-ci.com/java-fat-unicorn-team/ListOfGoods ) there are 3 survived mutations. Can you explain why is not important to fix?
2. Build report also has been executed with `-DskipTests=true`. Why?

**Comment by maksimk99** [comment]
1. I improved my tests.
2. I found about this and Travis CI used it for installing dependencies
https://docs.travis-ci.com/user/languages/java/#maven-dependency-management

**Comment by maksimk99** [comment]
I've merged it with last "add build at TravicCI" commit

**Comment by aleksieiev** [comment]
Here should be link to the commit, not the name of it
