### ISSUE TITLE
Add different validation plugins to the project

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/ListOfGoods#9]
Add the next plugins
1. checkstyle
2. PMD
3. PiTest - mutation tests

Task
1. Fix all errors from plugin warnings
2. Make impossible to build project if code is ugly

**Comment by maksimk99** [comment]
I've added these plugins and fixed all errors
Commit: https://github.com/java-fat-unicorn-team/ListOfGoods/commit/39cdc179ada312f42917f25738e4ec2943dcc3f8
